
'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("73d8fdc8-ef7b-4507-bcd3-8126b78c6f71")>
#Region "Metadatos de relaciones en EDM"
<Assembly: EdmRelationshipAttribute("SisFacModel", "FK_EMPLEADO_REFERENCE_CARGOS", "Cargos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Cargos), "Empleados", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Empleados), True)>
<Assembly: EdmRelationshipAttribute("SisFacModel", "FK_PRODUCTO_REFERENCE_CATEGORI", "Categorias", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Categorias), "Productos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Productos), True)>
<Assembly: EdmRelationshipAttribute("SisFacModel", "FK_CIUDADES_REFERENCE_REGIONES", "Regiones", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Regiones), "Ciudades", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Ciudades), True)>
<Assembly: EdmRelationshipAttribute("SisFacModel", "FK_CLIENTES_REFERENCE_CIUDADES", "Ciudades", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Ciudades), "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Clientes), True)>
<Assembly: EdmRelationshipAttribute("SisFacModel", "FK_EMPLEADO_REFERENCE_CIUDADES", "Ciudades", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Ciudades), "Empleados", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Empleados), True)>
<Assembly: EdmRelationshipAttribute("SisFacModel", "FK_CLIENTES_REFERENCE_REGIONES", "Regiones", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Regiones), "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Clientes), True)>
<Assembly: EdmRelationshipAttribute("SisFacModel", "FK_VENTAS_REFERENCE_CLIENTES", "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Clientes), "Ventas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Ventas), True)>
<Assembly: EdmRelationshipAttribute("SisFacModel", "FK_DETALLES_REFERENCE_PRODUCTO", "Productos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Productos), "DetallesVenta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DetallesVenta), True)>
<Assembly: EdmRelationshipAttribute("SisFacModel", "FK_DETALLES_REFERENCE_VENTAS", "Ventas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Ventas), "DetallesVenta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DetallesVenta), True)>
<Assembly: EdmRelationshipAttribute("SisFacModel", "FK_EMPLEADO_REFERENCE_REGIONES", "Regiones", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Regiones), "Empleados", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Empleados), True)>
<Assembly: EdmRelationshipAttribute("SisFacModel", "FK_VENTAS_REFERENCE_EMPLEADO", "Empleados", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Empleados), "Ventas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Ventas), True)>

#End Region

#Region "Contextos"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
Public Partial Class SisFacEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Inicializa un nuevo objeto SisFacEntities usando la cadena de conexión encontrada en la sección 'SisFacEntities' del archivo de configuración de la aplicación.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=SisFacEntities", "SisFacEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto SisFacEntities.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "SisFacEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto SisFacEntities.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "SisFacEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "Propiedades de ObjectSet"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Cargos() As ObjectSet(Of Cargos)
        Get
            If (_Cargos Is Nothing) Then
                _Cargos = MyBase.CreateObjectSet(Of Cargos)("Cargos")
            End If
            Return _Cargos
        End Get
    End Property

    Private _Cargos As ObjectSet(Of Cargos)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Categorias() As ObjectSet(Of Categorias)
        Get
            If (_Categorias Is Nothing) Then
                _Categorias = MyBase.CreateObjectSet(Of Categorias)("Categorias")
            End If
            Return _Categorias
        End Get
    End Property

    Private _Categorias As ObjectSet(Of Categorias)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Ciudades() As ObjectSet(Of Ciudades)
        Get
            If (_Ciudades Is Nothing) Then
                _Ciudades = MyBase.CreateObjectSet(Of Ciudades)("Ciudades")
            End If
            Return _Ciudades
        End Get
    End Property

    Private _Ciudades As ObjectSet(Of Ciudades)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Clientes() As ObjectSet(Of Clientes)
        Get
            If (_Clientes Is Nothing) Then
                _Clientes = MyBase.CreateObjectSet(Of Clientes)("Clientes")
            End If
            Return _Clientes
        End Get
    End Property

    Private _Clientes As ObjectSet(Of Clientes)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property DetallesVenta() As ObjectSet(Of DetallesVenta)
        Get
            If (_DetallesVenta Is Nothing) Then
                _DetallesVenta = MyBase.CreateObjectSet(Of DetallesVenta)("DetallesVenta")
            End If
            Return _DetallesVenta
        End Get
    End Property

    Private _DetallesVenta As ObjectSet(Of DetallesVenta)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Empleados() As ObjectSet(Of Empleados)
        Get
            If (_Empleados Is Nothing) Then
                _Empleados = MyBase.CreateObjectSet(Of Empleados)("Empleados")
            End If
            Return _Empleados
        End Get
    End Property

    Private _Empleados As ObjectSet(Of Empleados)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Productos() As ObjectSet(Of Productos)
        Get
            If (_Productos Is Nothing) Then
                _Productos = MyBase.CreateObjectSet(Of Productos)("Productos")
            End If
            Return _Productos
        End Get
    End Property

    Private _Productos As ObjectSet(Of Productos)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Regiones() As ObjectSet(Of Regiones)
        Get
            If (_Regiones Is Nothing) Then
                _Regiones = MyBase.CreateObjectSet(Of Regiones)("Regiones")
            End If
            Return _Regiones
        End Get
    End Property

    Private _Regiones As ObjectSet(Of Regiones)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Ventas() As ObjectSet(Of Ventas)
        Get
            If (_Ventas Is Nothing) Then
                _Ventas = MyBase.CreateObjectSet(Of Ventas)("Ventas")
            End If
            Return _Ventas
        End Get
    End Property

    Private _Ventas As ObjectSet(Of Ventas)

    #End Region
    #Region "Métodos AddTo"

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Cargos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToCargos(ByVal cargos As Cargos)
        MyBase.AddObject("Cargos", cargos)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Categorias. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToCategorias(ByVal categorias As Categorias)
        MyBase.AddObject("Categorias", categorias)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Ciudades. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToCiudades(ByVal ciudades As Ciudades)
        MyBase.AddObject("Ciudades", ciudades)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Clientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToClientes(ByVal clientes As Clientes)
        MyBase.AddObject("Clientes", clientes)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet DetallesVenta. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToDetallesVenta(ByVal detallesVenta As DetallesVenta)
        MyBase.AddObject("DetallesVenta", detallesVenta)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Empleados. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToEmpleados(ByVal empleados As Empleados)
        MyBase.AddObject("Empleados", empleados)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Productos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToProductos(ByVal productos As Productos)
        MyBase.AddObject("Productos", productos)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Regiones. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToRegiones(ByVal regiones As Regiones)
        MyBase.AddObject("Regiones", regiones)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Ventas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToVentas(ByVal ventas As Ventas)
        MyBase.AddObject("Ventas", ventas)
    End Sub

    #End Region
End Class

#End Region
#Region "Entidades"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SisFacModel", Name:="Cargos")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Cargos
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Cargos.
    ''' </summary>
    ''' <param name="idCargo">Valor inicial de la propiedad idCargo.</param>
    ''' <param name="cargo">Valor inicial de la propiedad Cargo.</param>
    Public Shared Function CreateCargos(idCargo As Global.System.Int32, cargo As Global.System.String) As Cargos
        Dim cargos as Cargos = New Cargos
        cargos.idCargo = idCargo
        cargos.Cargo = cargo
        Return cargos
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property idCargo() As Global.System.Int32
        Get
            Return _idCargo
        End Get
        Set
            If (_idCargo <> Value) Then
                OnidCargoChanging(value)
                ReportPropertyChanging("idCargo")
                _idCargo = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("idCargo")
                OnidCargoChanged()
            End If
        End Set
    End Property

    Private _idCargo As Global.System.Int32
    Private Partial Sub OnidCargoChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidCargoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Cargo() As Global.System.String
        Get
            Return _Cargo
        End Get
        Set
            OnCargoChanging(value)
            ReportPropertyChanging("Cargo")
            _Cargo = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Cargo")
            OnCargoChanged()
        End Set
    End Property

    Private _Cargo As Global.System.String
    Private Partial Sub OnCargoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCargoChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_EMPLEADO_REFERENCE_CARGOS", "Empleados")>
     Public Property Empleados() As EntityCollection(Of Empleados)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Empleados)("SisFacModel.FK_EMPLEADO_REFERENCE_CARGOS", "Empleados")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Empleados)("SisFacModel.FK_EMPLEADO_REFERENCE_CARGOS", "Empleados", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SisFacModel", Name:="Categorias")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Categorias
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Categorias.
    ''' </summary>
    ''' <param name="idCategoria">Valor inicial de la propiedad idCategoria.</param>
    ''' <param name="categoria">Valor inicial de la propiedad Categoria.</param>
    Public Shared Function CreateCategorias(idCategoria As Global.System.Int32, categoria As Global.System.String) As Categorias
        Dim categorias as Categorias = New Categorias
        categorias.idCategoria = idCategoria
        categorias.Categoria = categoria
        Return categorias
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property idCategoria() As Global.System.Int32
        Get
            Return _idCategoria
        End Get
        Set
            If (_idCategoria <> Value) Then
                OnidCategoriaChanging(value)
                ReportPropertyChanging("idCategoria")
                _idCategoria = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("idCategoria")
                OnidCategoriaChanged()
            End If
        End Set
    End Property

    Private _idCategoria As Global.System.Int32
    Private Partial Sub OnidCategoriaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidCategoriaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Categoria() As Global.System.String
        Get
            Return _Categoria
        End Get
        Set
            OnCategoriaChanging(value)
            ReportPropertyChanging("Categoria")
            _Categoria = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Categoria")
            OnCategoriaChanged()
        End Set
    End Property

    Private _Categoria As Global.System.String
    Private Partial Sub OnCategoriaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCategoriaChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_PRODUCTO_REFERENCE_CATEGORI", "Productos")>
     Public Property Productos() As EntityCollection(Of Productos)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Productos)("SisFacModel.FK_PRODUCTO_REFERENCE_CATEGORI", "Productos")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Productos)("SisFacModel.FK_PRODUCTO_REFERENCE_CATEGORI", "Productos", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SisFacModel", Name:="Ciudades")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Ciudades
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Ciudades.
    ''' </summary>
    ''' <param name="idCiudad">Valor inicial de la propiedad idCiudad.</param>
    ''' <param name="ciudad">Valor inicial de la propiedad Ciudad.</param>
    Public Shared Function CreateCiudades(idCiudad As Global.System.Int32, ciudad As Global.System.String) As Ciudades
        Dim ciudades as Ciudades = New Ciudades
        ciudades.idCiudad = idCiudad
        ciudades.Ciudad = ciudad
        Return ciudades
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property idCiudad() As Global.System.Int32
        Get
            Return _idCiudad
        End Get
        Set
            If (_idCiudad <> Value) Then
                OnidCiudadChanging(value)
                ReportPropertyChanging("idCiudad")
                _idCiudad = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("idCiudad")
                OnidCiudadChanged()
            End If
        End Set
    End Property

    Private _idCiudad As Global.System.Int32
    Private Partial Sub OnidCiudadChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidCiudadChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property idRegion() As Nullable(Of Global.System.Int32)
        Get
            Return _idRegion
        End Get
        Set
            OnidRegionChanging(value)
            ReportPropertyChanging("idRegion")
            _idRegion = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("idRegion")
            OnidRegionChanged()
        End Set
    End Property

    Private _idRegion As Nullable(Of Global.System.Int32)
    Private Partial Sub OnidRegionChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnidRegionChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Ciudad() As Global.System.String
        Get
            Return _Ciudad
        End Get
        Set
            OnCiudadChanging(value)
            ReportPropertyChanging("Ciudad")
            _Ciudad = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Ciudad")
            OnCiudadChanged()
        End Set
    End Property

    Private _Ciudad As Global.System.String
    Private Partial Sub OnCiudadChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCiudadChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_CIUDADES_REFERENCE_REGIONES", "Regiones")>
    Public Property Regiones() As Regiones
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Regiones)("SisFacModel.FK_CIUDADES_REFERENCE_REGIONES", "Regiones").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Regiones)("SisFacModel.FK_CIUDADES_REFERENCE_REGIONES", "Regiones").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property RegionesReference() As EntityReference(Of Regiones)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Regiones)("SisFacModel.FK_CIUDADES_REFERENCE_REGIONES", "Regiones")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Regiones)("SisFacModel.FK_CIUDADES_REFERENCE_REGIONES", "Regiones", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_CLIENTES_REFERENCE_CIUDADES", "Clientes")>
     Public Property Clientes() As EntityCollection(Of Clientes)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Clientes)("SisFacModel.FK_CLIENTES_REFERENCE_CIUDADES", "Clientes")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Clientes)("SisFacModel.FK_CLIENTES_REFERENCE_CIUDADES", "Clientes", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_EMPLEADO_REFERENCE_CIUDADES", "Empleados")>
     Public Property Empleados() As EntityCollection(Of Empleados)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Empleados)("SisFacModel.FK_EMPLEADO_REFERENCE_CIUDADES", "Empleados")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Empleados)("SisFacModel.FK_EMPLEADO_REFERENCE_CIUDADES", "Empleados", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SisFacModel", Name:="Clientes")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Clientes
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Clientes.
    ''' </summary>
    ''' <param name="rUT">Valor inicial de la propiedad RUT.</param>
    ''' <param name="rUTVer">Valor inicial de la propiedad RUTVer.</param>
    ''' <param name="empresa">Valor inicial de la propiedad Empresa.</param>
    ''' <param name="nombres">Valor inicial de la propiedad Nombres.</param>
    ''' <param name="apPaterno">Valor inicial de la propiedad ApPaterno.</param>
    ''' <param name="apMaterno">Valor inicial de la propiedad ApMaterno.</param>
    ''' <param name="estado">Valor inicial de la propiedad Estado.</param>
    Public Shared Function CreateClientes(rUT As Global.System.Int32, rUTVer As Global.System.String, empresa As Global.System.Boolean, nombres As Global.System.String, apPaterno As Global.System.String, apMaterno As Global.System.String, estado As Global.System.Boolean) As Clientes
        Dim clientes as Clientes = New Clientes
        clientes.RUT = rUT
        clientes.RUTVer = rUTVer
        clientes.Empresa = empresa
        clientes.Nombres = nombres
        clientes.ApPaterno = apPaterno
        clientes.ApMaterno = apMaterno
        clientes.Estado = estado
        Return clientes
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RUT() As Global.System.Int32
        Get
            Return _RUT
        End Get
        Set
            If (_RUT <> Value) Then
                OnRUTChanging(value)
                ReportPropertyChanging("RUT")
                _RUT = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("RUT")
                OnRUTChanged()
            End If
        End Set
    End Property

    Private _RUT As Global.System.Int32
    Private Partial Sub OnRUTChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnRUTChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RUTVer() As Global.System.String
        Get
            Return _RUTVer
        End Get
        Set
            OnRUTVerChanging(value)
            ReportPropertyChanging("RUTVer")
            _RUTVer = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("RUTVer")
            OnRUTVerChanged()
        End Set
    End Property

    Private _RUTVer As Global.System.String
    Private Partial Sub OnRUTVerChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRUTVerChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Empresa() As Global.System.Boolean
        Get
            Return _Empresa
        End Get
        Set
            OnEmpresaChanging(value)
            ReportPropertyChanging("Empresa")
            _Empresa = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Empresa")
            OnEmpresaChanged()
        End Set
    End Property

    Private _Empresa As Global.System.Boolean
    Private Partial Sub OnEmpresaChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnEmpresaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Nombres() As Global.System.String
        Get
            Return _Nombres
        End Get
        Set
            OnNombresChanging(value)
            ReportPropertyChanging("Nombres")
            _Nombres = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Nombres")
            OnNombresChanged()
        End Set
    End Property

    Private _Nombres As Global.System.String
    Private Partial Sub OnNombresChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNombresChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ApPaterno() As Global.System.String
        Get
            Return _ApPaterno
        End Get
        Set
            OnApPaternoChanging(value)
            ReportPropertyChanging("ApPaterno")
            _ApPaterno = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ApPaterno")
            OnApPaternoChanged()
        End Set
    End Property

    Private _ApPaterno As Global.System.String
    Private Partial Sub OnApPaternoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnApPaternoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ApMaterno() As Global.System.String
        Get
            Return _ApMaterno
        End Get
        Set
            OnApMaternoChanging(value)
            ReportPropertyChanging("ApMaterno")
            _ApMaterno = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ApMaterno")
            OnApMaternoChanged()
        End Set
    End Property

    Private _ApMaterno As Global.System.String
    Private Partial Sub OnApMaternoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnApMaternoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FechaNac() As Nullable(Of Global.System.DateTime)
        Get
            Return _FechaNac
        End Get
        Set
            OnFechaNacChanging(value)
            ReportPropertyChanging("FechaNac")
            _FechaNac = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("FechaNac")
            OnFechaNacChanged()
        End Set
    End Property

    Private _FechaNac As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnFechaNacChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnFechaNacChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Sexo() As Nullable(Of Global.System.Boolean)
        Get
            Return _Sexo
        End Get
        Set
            OnSexoChanging(value)
            ReportPropertyChanging("Sexo")
            _Sexo = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Sexo")
            OnSexoChanged()
        End Set
    End Property

    Private _Sexo As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnSexoChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnSexoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Email() As Global.System.String
        Get
            Return _Email
        End Get
        Set
            OnEmailChanging(value)
            ReportPropertyChanging("Email")
            _Email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Email")
            OnEmailChanged()
        End Set
    End Property

    Private _Email As Global.System.String
    Private Partial Sub OnEmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEmailChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Telefono() As Nullable(Of Global.System.Int32)
        Get
            Return _Telefono
        End Get
        Set
            OnTelefonoChanging(value)
            ReportPropertyChanging("Telefono")
            _Telefono = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Telefono")
            OnTelefonoChanged()
        End Set
    End Property

    Private _Telefono As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTelefonoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTelefonoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Direccion() As Global.System.String
        Get
            Return _Direccion
        End Get
        Set
            OnDireccionChanging(value)
            ReportPropertyChanging("Direccion")
            _Direccion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Direccion")
            OnDireccionChanged()
        End Set
    End Property

    Private _Direccion As Global.System.String
    Private Partial Sub OnDireccionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDireccionChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property idRegion() As Nullable(Of Global.System.Int32)
        Get
            Return _idRegion
        End Get
        Set
            OnidRegionChanging(value)
            ReportPropertyChanging("idRegion")
            _idRegion = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("idRegion")
            OnidRegionChanged()
        End Set
    End Property

    Private _idRegion As Nullable(Of Global.System.Int32)
    Private Partial Sub OnidRegionChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnidRegionChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property idCiudad() As Nullable(Of Global.System.Int32)
        Get
            Return _idCiudad
        End Get
        Set
            OnidCiudadChanging(value)
            ReportPropertyChanging("idCiudad")
            _idCiudad = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("idCiudad")
            OnidCiudadChanged()
        End Set
    End Property

    Private _idCiudad As Nullable(Of Global.System.Int32)
    Private Partial Sub OnidCiudadChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnidCiudadChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Estado() As Global.System.Boolean
        Get
            Return _Estado
        End Get
        Set
            OnEstadoChanging(value)
            ReportPropertyChanging("Estado")
            _Estado = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Estado")
            OnEstadoChanged()
        End Set
    End Property

    Private _Estado As Global.System.Boolean
    Private Partial Sub OnEstadoChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnEstadoChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_CLIENTES_REFERENCE_CIUDADES", "Ciudades")>
    Public Property Ciudades() As Ciudades
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Ciudades)("SisFacModel.FK_CLIENTES_REFERENCE_CIUDADES", "Ciudades").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Ciudades)("SisFacModel.FK_CLIENTES_REFERENCE_CIUDADES", "Ciudades").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CiudadesReference() As EntityReference(Of Ciudades)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Ciudades)("SisFacModel.FK_CLIENTES_REFERENCE_CIUDADES", "Ciudades")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Ciudades)("SisFacModel.FK_CLIENTES_REFERENCE_CIUDADES", "Ciudades", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_CLIENTES_REFERENCE_REGIONES", "Regiones")>
    Public Property Regiones() As Regiones
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Regiones)("SisFacModel.FK_CLIENTES_REFERENCE_REGIONES", "Regiones").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Regiones)("SisFacModel.FK_CLIENTES_REFERENCE_REGIONES", "Regiones").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property RegionesReference() As EntityReference(Of Regiones)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Regiones)("SisFacModel.FK_CLIENTES_REFERENCE_REGIONES", "Regiones")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Regiones)("SisFacModel.FK_CLIENTES_REFERENCE_REGIONES", "Regiones", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_VENTAS_REFERENCE_CLIENTES", "Ventas")>
     Public Property Ventas() As EntityCollection(Of Ventas)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Ventas)("SisFacModel.FK_VENTAS_REFERENCE_CLIENTES", "Ventas")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Ventas)("SisFacModel.FK_VENTAS_REFERENCE_CLIENTES", "Ventas", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SisFacModel", Name:="DetallesVenta")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class DetallesVenta
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto DetallesVenta.
    ''' </summary>
    ''' <param name="idDetalleVenta">Valor inicial de la propiedad idDetalleVenta.</param>
    ''' <param name="idVenta">Valor inicial de la propiedad idVenta.</param>
    ''' <param name="idProducto">Valor inicial de la propiedad idProducto.</param>
    ''' <param name="cantidad">Valor inicial de la propiedad Cantidad.</param>
    ''' <param name="valor">Valor inicial de la propiedad Valor.</param>
    Public Shared Function CreateDetallesVenta(idDetalleVenta As Global.System.Int64, idVenta As Global.System.Int32, idProducto As Global.System.Int32, cantidad As Global.System.Int32, valor As Global.System.Int32) As DetallesVenta
        Dim detallesVenta as DetallesVenta = New DetallesVenta
        detallesVenta.idDetalleVenta = idDetalleVenta
        detallesVenta.idVenta = idVenta
        detallesVenta.idProducto = idProducto
        detallesVenta.Cantidad = cantidad
        detallesVenta.Valor = valor
        Return detallesVenta
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property idDetalleVenta() As Global.System.Int64
        Get
            Return _idDetalleVenta
        End Get
        Set
            If (_idDetalleVenta <> Value) Then
                OnidDetalleVentaChanging(value)
                ReportPropertyChanging("idDetalleVenta")
                _idDetalleVenta = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("idDetalleVenta")
                OnidDetalleVentaChanged()
            End If
        End Set
    End Property

    Private _idDetalleVenta As Global.System.Int64
    Private Partial Sub OnidDetalleVentaChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub OnidDetalleVentaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property idVenta() As Global.System.Int32
        Get
            Return _idVenta
        End Get
        Set
            OnidVentaChanging(value)
            ReportPropertyChanging("idVenta")
            _idVenta = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("idVenta")
            OnidVentaChanged()
        End Set
    End Property

    Private _idVenta As Global.System.Int32
    Private Partial Sub OnidVentaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidVentaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property idProducto() As Global.System.Int32
        Get
            Return _idProducto
        End Get
        Set
            OnidProductoChanging(value)
            ReportPropertyChanging("idProducto")
            _idProducto = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("idProducto")
            OnidProductoChanged()
        End Set
    End Property

    Private _idProducto As Global.System.Int32
    Private Partial Sub OnidProductoChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidProductoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Cantidad() As Global.System.Int32
        Get
            Return _Cantidad
        End Get
        Set
            OnCantidadChanging(value)
            ReportPropertyChanging("Cantidad")
            _Cantidad = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Cantidad")
            OnCantidadChanged()
        End Set
    End Property

    Private _Cantidad As Global.System.Int32
    Private Partial Sub OnCantidadChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnCantidadChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Valor() As Global.System.Int32
        Get
            Return _Valor
        End Get
        Set
            OnValorChanging(value)
            ReportPropertyChanging("Valor")
            _Valor = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Valor")
            OnValorChanged()
        End Set
    End Property

    Private _Valor As Global.System.Int32
    Private Partial Sub OnValorChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnValorChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_DETALLES_REFERENCE_PRODUCTO", "Productos")>
    Public Property Productos() As Productos
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Productos)("SisFacModel.FK_DETALLES_REFERENCE_PRODUCTO", "Productos").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Productos)("SisFacModel.FK_DETALLES_REFERENCE_PRODUCTO", "Productos").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ProductosReference() As EntityReference(Of Productos)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Productos)("SisFacModel.FK_DETALLES_REFERENCE_PRODUCTO", "Productos")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Productos)("SisFacModel.FK_DETALLES_REFERENCE_PRODUCTO", "Productos", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_DETALLES_REFERENCE_VENTAS", "Ventas")>
    Public Property Ventas() As Ventas
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Ventas)("SisFacModel.FK_DETALLES_REFERENCE_VENTAS", "Ventas").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Ventas)("SisFacModel.FK_DETALLES_REFERENCE_VENTAS", "Ventas").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property VentasReference() As EntityReference(Of Ventas)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Ventas)("SisFacModel.FK_DETALLES_REFERENCE_VENTAS", "Ventas")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Ventas)("SisFacModel.FK_DETALLES_REFERENCE_VENTAS", "Ventas", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SisFacModel", Name:="Empleados")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Empleados
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Empleados.
    ''' </summary>
    ''' <param name="rUT">Valor inicial de la propiedad RUT.</param>
    ''' <param name="rUTVer">Valor inicial de la propiedad RUTVer.</param>
    ''' <param name="nombres">Valor inicial de la propiedad Nombres.</param>
    ''' <param name="apPaterno">Valor inicial de la propiedad ApPaterno.</param>
    ''' <param name="apMaterno">Valor inicial de la propiedad ApMaterno.</param>
    ''' <param name="idCargo">Valor inicial de la propiedad idCargo.</param>
    ''' <param name="password">Valor inicial de la propiedad Password.</param>
    ''' <param name="estado">Valor inicial de la propiedad Estado.</param>
    Public Shared Function CreateEmpleados(rUT As Global.System.Int32, rUTVer As Global.System.String, nombres As Global.System.String, apPaterno As Global.System.String, apMaterno As Global.System.String, idCargo As Global.System.Int32, password As Global.System.String, estado As Global.System.Boolean) As Empleados
        Dim empleados as Empleados = New Empleados
        empleados.RUT = rUT
        empleados.RUTVer = rUTVer
        empleados.Nombres = nombres
        empleados.ApPaterno = apPaterno
        empleados.ApMaterno = apMaterno
        empleados.idCargo = idCargo
        empleados.Password = password
        empleados.Estado = estado
        Return empleados
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RUT() As Global.System.Int32
        Get
            Return _RUT
        End Get
        Set
            If (_RUT <> Value) Then
                OnRUTChanging(value)
                ReportPropertyChanging("RUT")
                _RUT = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("RUT")
                OnRUTChanged()
            End If
        End Set
    End Property

    Private _RUT As Global.System.Int32
    Private Partial Sub OnRUTChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnRUTChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RUTVer() As Global.System.String
        Get
            Return _RUTVer
        End Get
        Set
            OnRUTVerChanging(value)
            ReportPropertyChanging("RUTVer")
            _RUTVer = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("RUTVer")
            OnRUTVerChanged()
        End Set
    End Property

    Private _RUTVer As Global.System.String
    Private Partial Sub OnRUTVerChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRUTVerChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Nombres() As Global.System.String
        Get
            Return _Nombres
        End Get
        Set
            OnNombresChanging(value)
            ReportPropertyChanging("Nombres")
            _Nombres = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Nombres")
            OnNombresChanged()
        End Set
    End Property

    Private _Nombres As Global.System.String
    Private Partial Sub OnNombresChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNombresChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ApPaterno() As Global.System.String
        Get
            Return _ApPaterno
        End Get
        Set
            OnApPaternoChanging(value)
            ReportPropertyChanging("ApPaterno")
            _ApPaterno = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ApPaterno")
            OnApPaternoChanged()
        End Set
    End Property

    Private _ApPaterno As Global.System.String
    Private Partial Sub OnApPaternoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnApPaternoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ApMaterno() As Global.System.String
        Get
            Return _ApMaterno
        End Get
        Set
            OnApMaternoChanging(value)
            ReportPropertyChanging("ApMaterno")
            _ApMaterno = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ApMaterno")
            OnApMaternoChanged()
        End Set
    End Property

    Private _ApMaterno As Global.System.String
    Private Partial Sub OnApMaternoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnApMaternoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FechaNac() As Nullable(Of Global.System.DateTime)
        Get
            Return _FechaNac
        End Get
        Set
            OnFechaNacChanging(value)
            ReportPropertyChanging("FechaNac")
            _FechaNac = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("FechaNac")
            OnFechaNacChanged()
        End Set
    End Property

    Private _FechaNac As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnFechaNacChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnFechaNacChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Sexo() As Nullable(Of Global.System.Boolean)
        Get
            Return _Sexo
        End Get
        Set
            OnSexoChanging(value)
            ReportPropertyChanging("Sexo")
            _Sexo = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Sexo")
            OnSexoChanged()
        End Set
    End Property

    Private _Sexo As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnSexoChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnSexoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Email() As Global.System.String
        Get
            Return _Email
        End Get
        Set
            OnEmailChanging(value)
            ReportPropertyChanging("Email")
            _Email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Email")
            OnEmailChanged()
        End Set
    End Property

    Private _Email As Global.System.String
    Private Partial Sub OnEmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEmailChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Telefono() As Nullable(Of Global.System.Int32)
        Get
            Return _Telefono
        End Get
        Set
            OnTelefonoChanging(value)
            ReportPropertyChanging("Telefono")
            _Telefono = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Telefono")
            OnTelefonoChanged()
        End Set
    End Property

    Private _Telefono As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTelefonoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTelefonoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Direccion() As Global.System.String
        Get
            Return _Direccion
        End Get
        Set
            OnDireccionChanging(value)
            ReportPropertyChanging("Direccion")
            _Direccion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Direccion")
            OnDireccionChanged()
        End Set
    End Property

    Private _Direccion As Global.System.String
    Private Partial Sub OnDireccionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDireccionChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property idRegion() As Nullable(Of Global.System.Int32)
        Get
            Return _idRegion
        End Get
        Set
            OnidRegionChanging(value)
            ReportPropertyChanging("idRegion")
            _idRegion = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("idRegion")
            OnidRegionChanged()
        End Set
    End Property

    Private _idRegion As Nullable(Of Global.System.Int32)
    Private Partial Sub OnidRegionChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnidRegionChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property idCiudad() As Nullable(Of Global.System.Int32)
        Get
            Return _idCiudad
        End Get
        Set
            OnidCiudadChanging(value)
            ReportPropertyChanging("idCiudad")
            _idCiudad = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("idCiudad")
            OnidCiudadChanged()
        End Set
    End Property

    Private _idCiudad As Nullable(Of Global.System.Int32)
    Private Partial Sub OnidCiudadChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnidCiudadChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property idCargo() As Global.System.Int32
        Get
            Return _idCargo
        End Get
        Set
            OnidCargoChanging(value)
            ReportPropertyChanging("idCargo")
            _idCargo = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("idCargo")
            OnidCargoChanged()
        End Set
    End Property

    Private _idCargo As Global.System.Int32
    Private Partial Sub OnidCargoChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidCargoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Password() As Global.System.String
        Get
            Return _Password
        End Get
        Set
            OnPasswordChanging(value)
            ReportPropertyChanging("Password")
            _Password = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Password")
            OnPasswordChanged()
        End Set
    End Property

    Private _Password As Global.System.String
    Private Partial Sub OnPasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPasswordChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Estado() As Global.System.Boolean
        Get
            Return _Estado
        End Get
        Set
            OnEstadoChanging(value)
            ReportPropertyChanging("Estado")
            _Estado = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Estado")
            OnEstadoChanged()
        End Set
    End Property

    Private _Estado As Global.System.Boolean
    Private Partial Sub OnEstadoChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnEstadoChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_EMPLEADO_REFERENCE_CARGOS", "Cargos")>
    Public Property Cargos() As Cargos
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cargos)("SisFacModel.FK_EMPLEADO_REFERENCE_CARGOS", "Cargos").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cargos)("SisFacModel.FK_EMPLEADO_REFERENCE_CARGOS", "Cargos").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CargosReference() As EntityReference(Of Cargos)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cargos)("SisFacModel.FK_EMPLEADO_REFERENCE_CARGOS", "Cargos")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Cargos)("SisFacModel.FK_EMPLEADO_REFERENCE_CARGOS", "Cargos", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_EMPLEADO_REFERENCE_CIUDADES", "Ciudades")>
    Public Property Ciudades() As Ciudades
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Ciudades)("SisFacModel.FK_EMPLEADO_REFERENCE_CIUDADES", "Ciudades").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Ciudades)("SisFacModel.FK_EMPLEADO_REFERENCE_CIUDADES", "Ciudades").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CiudadesReference() As EntityReference(Of Ciudades)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Ciudades)("SisFacModel.FK_EMPLEADO_REFERENCE_CIUDADES", "Ciudades")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Ciudades)("SisFacModel.FK_EMPLEADO_REFERENCE_CIUDADES", "Ciudades", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_EMPLEADO_REFERENCE_REGIONES", "Regiones")>
    Public Property Regiones() As Regiones
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Regiones)("SisFacModel.FK_EMPLEADO_REFERENCE_REGIONES", "Regiones").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Regiones)("SisFacModel.FK_EMPLEADO_REFERENCE_REGIONES", "Regiones").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property RegionesReference() As EntityReference(Of Regiones)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Regiones)("SisFacModel.FK_EMPLEADO_REFERENCE_REGIONES", "Regiones")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Regiones)("SisFacModel.FK_EMPLEADO_REFERENCE_REGIONES", "Regiones", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_VENTAS_REFERENCE_EMPLEADO", "Ventas")>
     Public Property Ventas() As EntityCollection(Of Ventas)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Ventas)("SisFacModel.FK_VENTAS_REFERENCE_EMPLEADO", "Ventas")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Ventas)("SisFacModel.FK_VENTAS_REFERENCE_EMPLEADO", "Ventas", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SisFacModel", Name:="Productos")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Productos
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Productos.
    ''' </summary>
    ''' <param name="idProducto">Valor inicial de la propiedad idProducto.</param>
    ''' <param name="idCategoria">Valor inicial de la propiedad idCategoria.</param>
    ''' <param name="producto">Valor inicial de la propiedad Producto.</param>
    ''' <param name="cantidad">Valor inicial de la propiedad Cantidad.</param>
    ''' <param name="valor">Valor inicial de la propiedad Valor.</param>
    ''' <param name="estado">Valor inicial de la propiedad Estado.</param>
    Public Shared Function CreateProductos(idProducto As Global.System.Int32, idCategoria As Global.System.Int32, producto As Global.System.String, cantidad As Global.System.Int32, valor As Global.System.Int32, estado As Global.System.Boolean) As Productos
        Dim productos as Productos = New Productos
        productos.idProducto = idProducto
        productos.idCategoria = idCategoria
        productos.Producto = producto
        productos.Cantidad = cantidad
        productos.Valor = valor
        productos.Estado = estado
        Return productos
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property idProducto() As Global.System.Int32
        Get
            Return _idProducto
        End Get
        Set
            If (_idProducto <> Value) Then
                OnidProductoChanging(value)
                ReportPropertyChanging("idProducto")
                _idProducto = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("idProducto")
                OnidProductoChanged()
            End If
        End Set
    End Property

    Private _idProducto As Global.System.Int32
    Private Partial Sub OnidProductoChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidProductoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property idCategoria() As Global.System.Int32
        Get
            Return _idCategoria
        End Get
        Set
            OnidCategoriaChanging(value)
            ReportPropertyChanging("idCategoria")
            _idCategoria = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("idCategoria")
            OnidCategoriaChanged()
        End Set
    End Property

    Private _idCategoria As Global.System.Int32
    Private Partial Sub OnidCategoriaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidCategoriaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Producto() As Global.System.String
        Get
            Return _Producto
        End Get
        Set
            OnProductoChanging(value)
            ReportPropertyChanging("Producto")
            _Producto = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Producto")
            OnProductoChanged()
        End Set
    End Property

    Private _Producto As Global.System.String
    Private Partial Sub OnProductoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnProductoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Cantidad() As Global.System.Int32
        Get
            Return _Cantidad
        End Get
        Set
            OnCantidadChanging(value)
            ReportPropertyChanging("Cantidad")
            _Cantidad = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Cantidad")
            OnCantidadChanged()
        End Set
    End Property

    Private _Cantidad As Global.System.Int32
    Private Partial Sub OnCantidadChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnCantidadChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Valor() As Global.System.Int32
        Get
            Return _Valor
        End Get
        Set
            OnValorChanging(value)
            ReportPropertyChanging("Valor")
            _Valor = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Valor")
            OnValorChanged()
        End Set
    End Property

    Private _Valor As Global.System.Int32
    Private Partial Sub OnValorChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnValorChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Comentario() As Global.System.String
        Get
            Return _Comentario
        End Get
        Set
            OnComentarioChanging(value)
            ReportPropertyChanging("Comentario")
            _Comentario = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Comentario")
            OnComentarioChanged()
        End Set
    End Property

    Private _Comentario As Global.System.String
    Private Partial Sub OnComentarioChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnComentarioChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Estado() As Global.System.Boolean
        Get
            Return _Estado
        End Get
        Set
            OnEstadoChanging(value)
            ReportPropertyChanging("Estado")
            _Estado = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Estado")
            OnEstadoChanged()
        End Set
    End Property

    Private _Estado As Global.System.Boolean
    Private Partial Sub OnEstadoChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnEstadoChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_PRODUCTO_REFERENCE_CATEGORI", "Categorias")>
    Public Property Categorias() As Categorias
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Categorias)("SisFacModel.FK_PRODUCTO_REFERENCE_CATEGORI", "Categorias").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Categorias)("SisFacModel.FK_PRODUCTO_REFERENCE_CATEGORI", "Categorias").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CategoriasReference() As EntityReference(Of Categorias)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Categorias)("SisFacModel.FK_PRODUCTO_REFERENCE_CATEGORI", "Categorias")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Categorias)("SisFacModel.FK_PRODUCTO_REFERENCE_CATEGORI", "Categorias", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_DETALLES_REFERENCE_PRODUCTO", "DetallesVenta")>
     Public Property DetallesVenta() As EntityCollection(Of DetallesVenta)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DetallesVenta)("SisFacModel.FK_DETALLES_REFERENCE_PRODUCTO", "DetallesVenta")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DetallesVenta)("SisFacModel.FK_DETALLES_REFERENCE_PRODUCTO", "DetallesVenta", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SisFacModel", Name:="Regiones")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Regiones
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Regiones.
    ''' </summary>
    ''' <param name="idRegion">Valor inicial de la propiedad idRegion.</param>
    ''' <param name="region">Valor inicial de la propiedad Region.</param>
    Public Shared Function CreateRegiones(idRegion As Global.System.Int32, region As Global.System.String) As Regiones
        Dim regiones as Regiones = New Regiones
        regiones.idRegion = idRegion
        regiones.Region = region
        Return regiones
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property idRegion() As Global.System.Int32
        Get
            Return _idRegion
        End Get
        Set
            If (_idRegion <> Value) Then
                OnidRegionChanging(value)
                ReportPropertyChanging("idRegion")
                _idRegion = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("idRegion")
                OnidRegionChanged()
            End If
        End Set
    End Property

    Private _idRegion As Global.System.Int32
    Private Partial Sub OnidRegionChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidRegionChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Region() As Global.System.String
        Get
            Return _Region
        End Get
        Set
            OnRegionChanging(value)
            ReportPropertyChanging("Region")
            _Region = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Region")
            OnRegionChanged()
        End Set
    End Property

    Private _Region As Global.System.String
    Private Partial Sub OnRegionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRegionChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_CIUDADES_REFERENCE_REGIONES", "Ciudades")>
     Public Property Ciudades() As EntityCollection(Of Ciudades)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Ciudades)("SisFacModel.FK_CIUDADES_REFERENCE_REGIONES", "Ciudades")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Ciudades)("SisFacModel.FK_CIUDADES_REFERENCE_REGIONES", "Ciudades", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_CLIENTES_REFERENCE_REGIONES", "Clientes")>
     Public Property Clientes() As EntityCollection(Of Clientes)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Clientes)("SisFacModel.FK_CLIENTES_REFERENCE_REGIONES", "Clientes")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Clientes)("SisFacModel.FK_CLIENTES_REFERENCE_REGIONES", "Clientes", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_EMPLEADO_REFERENCE_REGIONES", "Empleados")>
     Public Property Empleados() As EntityCollection(Of Empleados)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Empleados)("SisFacModel.FK_EMPLEADO_REFERENCE_REGIONES", "Empleados")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Empleados)("SisFacModel.FK_EMPLEADO_REFERENCE_REGIONES", "Empleados", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SisFacModel", Name:="Ventas")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Ventas
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Ventas.
    ''' </summary>
    ''' <param name="idVenta">Valor inicial de la propiedad idVenta.</param>
    ''' <param name="tipoVenta">Valor inicial de la propiedad TipoVenta.</param>
    ''' <param name="rUTEmpleado">Valor inicial de la propiedad RUTEmpleado.</param>
    ''' <param name="rUTCliente">Valor inicial de la propiedad RUTCliente.</param>
    ''' <param name="fecha">Valor inicial de la propiedad Fecha.</param>
    Public Shared Function CreateVentas(idVenta As Global.System.Int32, tipoVenta As Global.System.Int32, rUTEmpleado As Global.System.Int32, rUTCliente As Global.System.Int32, fecha As Global.System.DateTime) As Ventas
        Dim ventas as Ventas = New Ventas
        ventas.idVenta = idVenta
        ventas.TipoVenta = tipoVenta
        ventas.RUTEmpleado = rUTEmpleado
        ventas.RUTCliente = rUTCliente
        ventas.Fecha = fecha
        Return ventas
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property idVenta() As Global.System.Int32
        Get
            Return _idVenta
        End Get
        Set
            If (_idVenta <> Value) Then
                OnidVentaChanging(value)
                ReportPropertyChanging("idVenta")
                _idVenta = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("idVenta")
                OnidVentaChanged()
            End If
        End Set
    End Property

    Private _idVenta As Global.System.Int32
    Private Partial Sub OnidVentaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidVentaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property TipoVenta() As Global.System.Int32
        Get
            Return _TipoVenta
        End Get
        Set
            OnTipoVentaChanging(value)
            ReportPropertyChanging("TipoVenta")
            _TipoVenta = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TipoVenta")
            OnTipoVentaChanged()
        End Set
    End Property

    Private _TipoVenta As Global.System.Int32
    Private Partial Sub OnTipoVentaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnTipoVentaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RUTEmpleado() As Global.System.Int32
        Get
            Return _RUTEmpleado
        End Get
        Set
            OnRUTEmpleadoChanging(value)
            ReportPropertyChanging("RUTEmpleado")
            _RUTEmpleado = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("RUTEmpleado")
            OnRUTEmpleadoChanged()
        End Set
    End Property

    Private _RUTEmpleado As Global.System.Int32
    Private Partial Sub OnRUTEmpleadoChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnRUTEmpleadoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RUTCliente() As Global.System.Int32
        Get
            Return _RUTCliente
        End Get
        Set
            OnRUTClienteChanging(value)
            ReportPropertyChanging("RUTCliente")
            _RUTCliente = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("RUTCliente")
            OnRUTClienteChanged()
        End Set
    End Property

    Private _RUTCliente As Global.System.Int32
    Private Partial Sub OnRUTClienteChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnRUTClienteChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Fecha() As Global.System.DateTime
        Get
            Return _Fecha
        End Get
        Set
            OnFechaChanging(value)
            ReportPropertyChanging("Fecha")
            _Fecha = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Fecha")
            OnFechaChanged()
        End Set
    End Property

    Private _Fecha As Global.System.DateTime
    Private Partial Sub OnFechaChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnFechaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Descuento() As Nullable(Of Global.System.Int32)
        Get
            Return _Descuento
        End Get
        Set
            OnDescuentoChanging(value)
            ReportPropertyChanging("Descuento")
            _Descuento = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Descuento")
            OnDescuentoChanged()
        End Set
    End Property

    Private _Descuento As Nullable(Of Global.System.Int32)
    Private Partial Sub OnDescuentoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnDescuentoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Pagado() As Nullable(Of Global.System.Boolean)
        Get
            Return _Pagado
        End Get
        Set
            OnPagadoChanging(value)
            ReportPropertyChanging("Pagado")
            _Pagado = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Pagado")
            OnPagadoChanged()
        End Set
    End Property

    Private _Pagado As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnPagadoChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnPagadoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Entregado() As Nullable(Of Global.System.Boolean)
        Get
            Return _Entregado
        End Get
        Set
            OnEntregadoChanging(value)
            ReportPropertyChanging("Entregado")
            _Entregado = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Entregado")
            OnEntregadoChanged()
        End Set
    End Property

    Private _Entregado As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnEntregadoChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnEntregadoChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_VENTAS_REFERENCE_CLIENTES", "Clientes")>
    Public Property Clientes() As Clientes
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Clientes)("SisFacModel.FK_VENTAS_REFERENCE_CLIENTES", "Clientes").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Clientes)("SisFacModel.FK_VENTAS_REFERENCE_CLIENTES", "Clientes").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ClientesReference() As EntityReference(Of Clientes)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Clientes)("SisFacModel.FK_VENTAS_REFERENCE_CLIENTES", "Clientes")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Clientes)("SisFacModel.FK_VENTAS_REFERENCE_CLIENTES", "Clientes", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_DETALLES_REFERENCE_VENTAS", "DetallesVenta")>
     Public Property DetallesVenta() As EntityCollection(Of DetallesVenta)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DetallesVenta)("SisFacModel.FK_DETALLES_REFERENCE_VENTAS", "DetallesVenta")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DetallesVenta)("SisFacModel.FK_DETALLES_REFERENCE_VENTAS", "DetallesVenta", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SisFacModel", "FK_VENTAS_REFERENCE_EMPLEADO", "Empleados")>
    Public Property Empleados() As Empleados
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Empleados)("SisFacModel.FK_VENTAS_REFERENCE_EMPLEADO", "Empleados").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Empleados)("SisFacModel.FK_VENTAS_REFERENCE_EMPLEADO", "Empleados").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property EmpleadosReference() As EntityReference(Of Empleados)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Empleados)("SisFacModel.FK_VENTAS_REFERENCE_EMPLEADO", "Empleados")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Empleados)("SisFacModel.FK_VENTAS_REFERENCE_EMPLEADO", "Empleados", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

